### ISSUE TITLE
What is the license of this driver?

### ISSUE THREAD

**Issue by CodeOhms** [Ryochan7/FakerInput#2]
Hi,

I would like to use this driver in a project of mine, but need to know what the license is or negotiate one to use it. I hope to hear from you soon.

Best regards and a happy new year

**Comment by Ryochan7** [comment]
Work on this project was mostly a one time deal. It was meant to update and deprecate the original VMulti driver that I had used for Touchmote and antimicro in the past. VMulti was derived from code in the vhidmini2 project provided by Microsoft code samples.

https://github.com/djpnewton/vmulti
https://github.com/microsoft/Windows-driver-samples/tree/master/hid/vhidmini2

The Microsoft code samples are provided under the MS-PL license and the VMulti project is MIT licensed. I guess I can continue with licensing this derived project under the MIT license. I will add license info to the repo later.

There are some small update ideas I have had for this project but I have been more invested in other projects. My gamepad mapper experiments have benefited from using this driver rather than SendInput.

**Comment by CodeOhms** [comment]
Thanks for the quick reply Ryochan7 :+1:.
My project is in its early research stages, so no rush.
If you like, I could try to write the update ideas that you had in my own fork as a thank you for providing this driver free, signed and permissively licensed :smiley:.
